# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9707d9570d5c61a52ec89c3597b9f5774bb5b39ea54fffd8e4e2b80c9ab655b3fd9df656ac593ad3e3dd2268d143424667c0578d82febebfb4da9dd5a244b49e

test:
  secret_key_base: 4562fa4ab0fcad03e74264b5135bbfec17a5212729ea12e6ce923501d35083841d06d63bb1a40c9285b06ca9e83aa26f1cddff8ab93ebceeb32971c181e1845f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
